yaw_intervals:
  - [-51, -33.33]
  - [-33.33, -16.67]
  - [-16.67, 0]
  - [0, 16.67]
  - [16.67, 33.33]
  - [33.33, 51]

pitch_intervals:
  - [-41, -26.67]
  - [-26.67, -13.33]
  - [-13.33, 0]
  - [0, 13.33]
  - [13.33, 26.67]
  - [26.67, 41]

roll_intervals:
  - [-31, -20]
  - [-20, -10]
  - [-10, 0]
  - [0, 10]
  - [10, 20]
  - [20, 31]

val_set : "facescape" # facescape / biwi / AFLW2000
# val_set_path: "C:\\Mahdi\\development\\TokenHPE-main\\datasets\\BIWI.npz"
 
# val_set_path = "E:/Mahdi/Databases/3D_DB_(50_40_30)_valset_singleExpressions_60_Subjects_300W_RzRyRx_(+y-p-r)_rotation_convention" 
val_set_path = "E:/Mahdi/Databases/3D_DB_(50_40_30)_valset_singleExpressions_60_Subjects_300W_RzRyRx_(+y+p+r)_rotation_convention(jpg)" 
# val_set_path= "C:\\Mahdi\\development\\TokenHPE-main\\datasets\\AFLW2000"